default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { ENV.fetch("USER", "postgres") } %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "expenseflow_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_TEST_NAME") { "expenseflow_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "expenseflow_production" } %>
  url: <%= ENV["DATABASE_URL"] %>
